POST http://localhost:5000/transactions/addIncomeTransaction 
Content-Type: application/json

{
"incomeText": "KanyeOne",
"incomeAmount": 440
}

###

POST http://localhost:5000/transactions/addExpenseTransaction 
Content-Type: application/json

{
"expenseText": "KanyeOne",
"expenseAmount": 200
}

###

DELETE http://localhost:5000/transactions/deleteIncomeTransaction/5fa576e0df096b078c35c115
Content-Type: application/json

###

DELETE http://localhost:5000/transactions/deleteExpenseTransaction/5fa2dbad7949b21970f988e3
Content-Type: application/json

###

GET http://localhost:5000/transactions/getAll
Content-Type: application/json


###

POST http://localhost:5000/register
Content-Type: application/json

{
"username": "KanyeOne",
"password": "cacacelul2"
}

###

POST http://localhost:5000/login
Content-Type: application/json

{
"username": "KanyeOne",
"password": "cacacelul34"
}